[site]
name = "offlineisbetter"
style = "dark"
icon = "favicon.ico"

[analytics]
tag = "analytics-tag.html"

[menu]
names = [
    "home",
    "about",
    "contact",
]
links = [
    "/",
    "/about",
    "/contact",
]

[media]
include = []
