[site]
name = "offlineisbetter"
style = "dark"
icon = "favicon.ico"

[menu]
names = [
    "about",
    "metrics",
    "contact",
]
links = [
    "/",
    "/metrics",
    "/contact",
]

[media]
include = []
